stages:
  - prepare
  - build
  - deploy

image: docker:${DOCKER_VERSION}
variables:
  DOCKER_BUILDKIT: 1
  DOCKER_VERSION: 20.10.17

.docker_init_template:
  - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY

.ssh_init_template:
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - chmod 700 ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - eval $(ssh-agent -s)
  - ssh-add ~/.ssh/id_rsa

install:
  stage: prepare
  services:
    - name: docker:${DOCKER_VERSION}-dind
      command: ["--registry-mirror", "https://registry-proxy.x5.money"]
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - node_modules
      policy: pull-push
  before_script:
    - !reference [.docker_init_template]
  script:
    - mkdir -p node_modules

    - >
      docker build
      --file docker/node/Dockerfile
      --target install
      --tag $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-install
      .

    - rm -rf node_modules

    - docker create --name node $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-install
    - docker cp node:/app/node_modules $CI_PROJECT_DIR/

.build_production_template:
  stage: build
  services:
    - name: docker:${DOCKER_VERSION}-dind
      command: ["--registry-mirror", "https://registry-proxy.x5.money"]
  cache:
    - key:
        files:
          - package-lock.json
      paths:
        - node_modules
      policy: pull
    - key: next-cache-${PROJECT_NAME}-${CI_COMMIT_REF_SLUG}
      paths:
        - .next/cache
      policy: pull-push
  before_script:
    - !reference [.docker_init_template]
  script:
    - mkdir -p .next/cache

    - >
      docker build
      --file docker/node/Dockerfile
      --build-arg BUILDKIT_INLINE_CACHE=1
      --cache-from $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-$PROJECT_NAME
      --target builder
      --tag $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-$PROJECT_NAME
      --build-arg "NEXT_PUBLIC_FOOTER=$NEXT_PUBLIC_FOOTER"
      .

    - rm -rf .next/cache

    - docker create --name main_page $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-$PROJECT_NAME
    - docker cp main_page:/app/.next/cache $CI_PROJECT_DIR/.next/cache

    - docker push $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-$PROJECT_NAME
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

.deploy_production_template:
  stage: deploy
  environment:
    name: production-${PROJECT_NAME}
  variables:
    COMPOSE_PROJECT_NAME: ${PROJECT_NAME}_main_page
    LANDING_IMAGE: $DOCKER_REGISTRY_PATH:$CI_COMMIT_REF_NAME-$PROJECT_NAME
    DOCKER_HOST: $DEPLOY_PROD_DOCKER_HOST
  before_script:
    - !reference [.ssh_init_template]
    - !reference [.docker_init_template]
  script:
    - docker compose pull main_page

    - docker compose up -d --wait
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

build_call-funcom:
  extends: .build_production_template
  variables:
    PROJECT_NAME: call-funcom
    NEXT_PUBLIC_FOOTER: "ИП Круковский Андрей Николаевич<br></br>ИНН: 780535623621 ОГРН: 322784700279882<br></br>EMAIL: promohelper@proton.me<br></br><a href=\"https://t.me/stick_support\">TELEGRAM</a><br></br><a href=\"https://docs.google.com/document/d/1wUCaCHZGo42OHUtUZcL2e1y80lrDDIext-Qs7N5UFZw/edit?usp=sharing\">Пользовательское соглашение</a><br></br><a href=\"https://docs.google.com/document/d/11ntwB7fqvLM1RYB1-W0y4046AkH3e8qhNb3qyWWETo8/edit?usp=sharing\">Политика обработки данных</a><br></br><a href=\"http://cdn-pranks.x5.money/tariffs.pdf\">Тарифы</a>"

deploy_production_call-funcom:
  extends: .deploy_production_template
  variables:
    PROJECT_NAME: call-funcom
    VIRTUAL_HOST: call-fun.com

build_pay-callpro:
  extends: .build_production_template
  variables:
    PROJECT_NAME: pay-callpro
    NEXT_PUBLIC_FOOTER: "ИП Алексеева Алина Владимировна<br></br>ИНН: 780530945488 ОГРН: 323784700256649<br></br>EMAIL: promohelper@proton.me<br></br><a href=\"https://t.me/stick_support\">TELEGRAM</a><br></br><a href=\"https://docs.google.com/document/d/1wUCaCHZGo42OHUtUZcL2e1y80lrDDIext-Qs7N5UFZw/edit?usp=sharing\">Пользовательское соглашение</a><br></br><a href=\"https://docs.google.com/document/d/11ntwB7fqvLM1RYB1-W0y4046AkH3e8qhNb3qyWWETo8/edit?usp=sharing\">Политика обработки данных</a><br></br><a href=\"http://cdn-pranks.x5.money/tariffs.pdf\">Тарифы</a>"

deploy_production_pay-callpro:
  extends: .deploy_production_template
  variables:
    PROJECT_NAME: pay-callpro
    VIRTUAL_HOST: pay-call.pro